/*
 * Generated by the Gradle `init` task, then shaped for six — see docs/android.md.
 *
 * `google()` is here for androidx, which `:core` already needs — androidx.sqlite is a KMP artifact
 * with a JVM target, so the storage layer is testable without an Android device — and which `:app`
 * will need for everything else.
 */

pluginManagement {
    repositories {
        google()
        // repo.maven.apache.org is not reachable from this machine (403); Google's own GCS mirror
        // of Maven Central is, and it serves the identical artifacts. `mavenCentral()` stays behind
        // it so a network where the canonical host works loses nothing.
        maven { url = uri("https://maven-central.storage-download.googleapis.com/maven2/") }
        mavenCentral()
        gradlePluginPortal()
    }
}

// `gradle init` puts the foojay toolchain resolver here. It is gone on purpose: no module declares a
// toolchain, so it would only ever be a silent invitation to download a JDK mid-build.

dependencyResolutionManagement {
    repositories {
        google()
        // repo.maven.apache.org is not reachable from this machine (403); Google's own GCS mirror
        // of Maven Central is, and it serves the identical artifacts. `mavenCentral()` stays behind
        // it so a network where the canonical host works loses nothing.
        maven { url = uri("https://maven-central.storage-download.googleapis.com/maven2/") }
        mavenCentral()
    }
}

rootProject.name = "six-android"

include("core")
include("app")
