#!/bin/sh
# Vendors Bergamot's JavaScript glue into six/Translation/Payload/, as Swift.
#
#   ./scripts/bergamot-payload.sh [ref]
#
# Bergamot is delivered in two halves and only one of them is downloadable at run time. The
# `.wasm` — 4.9 MB of Marian compiled by Emscripten — is a record in Mozilla's Remote Settings
# and six fetches it like Firefox does, on demand and into the cache. The other half is the
# glue Emscripten generates beside it: `loadBergamot(Module)`, the embind bindings, the heap.
# That is *source*, it is version-locked to the wasm it was generated with, and it is nowhere
# public but the Firefox tree — so it is vendored here rather than downloaded, the same bargain
# blocking-payload.sh makes with AdGuard's scriptlets.
#
# The output is committed, so building six needs no network and no Node at all. Run this only
# when the pinned wasm version moves; the version the glue belongs to is written beside it, and
# `BergamotStore` refuses a wasm record that does not match.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/six/Translation/Payload"
ref=${1:-main}
repo=https://api.github.com/repos/mozilla-firefox/firefox/contents
dir=toolkit/components/translations/bergamot-translator

PYTHON=${PYTHON:-$(command -v python3 || command -v python)}
[ -n "$PYTHON" ] || { echo "no python on PATH" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

fetch() {
    curl -sS --max-time 120 "$repo/$dir/$1?ref=$ref" > "$work/$1.json"
    "$PYTHON" - "$work/$1.json" "$work/$1" <<'PY'
import base64, json, sys
record = json.load(open(sys.argv[1], encoding="utf-8"))
if "content" not in record:
    sys.exit("github: " + str(record.get("message")))
open(sys.argv[2], "wb").write(base64.b64decode(record["content"]))
print(record["sha"])
PY
}

blob=$(fetch bergamot-translator.js)
fetch LICENSE > /dev/null
echo "bergamot-translator.js @ $ref — blob $blob"

# The version the glue was generated from is written into the glue itself, and it is the one
# thing that must agree with the record `BergamotCatalog` picks out of Remote Settings.
version=$(sed -n 's/.*BERGAMOT_VERSION_FULL = "v\([0-9.]*\).*/\1/p' "$work/bergamot-translator.js" | head -1)
[ -n "$version" ] || { echo "no BERGAMOT_VERSION_FULL in the glue — the build script upstream changed" >&2; exit 1; }
echo "bergamot v$version"

mkdir -p "$out"
cp "$work/LICENSE" "$out/BERGAMOT-LICENSE"

{
    cat <<HEADER
// AUTO-GENERATED by scripts/bergamot-payload.sh. Do not edit.
//
// Emscripten's glue for bergamot-translator v$version, from the Firefox tree at
// $dir/bergamot-translator.js
// (blob $blob), under the MPL 2.0 — the licence is beside this file as BERGAMOT-LICENSE.
//
// It is Swift only so that it can be written to disk on a front that has no resource bundle to
// read it out of. \`BergamotRuntime\` drops it beside the wasm in six's cache and the sandbox page
// loads it from there; nothing here is ever parsed by Swift.
//
// The payload itself is Linux and Windows only — those are the fronts that translate with Bergamot,
// and a hundred kilobytes of Emscripten in the Mac binary would buy nothing. The *version* is
// declared on every platform so that the rest of the feature still type-checks where it is inert,
// which is the whole reason a Mac build is worth anything to the Linux front.
import Foundation

nonisolated enum BergamotGlue {
    /// The wasm release this glue was generated with. A record for any other one is refused:
    /// embind bindings are generated per build, and a mismatched pair fails as a missing symbol
    /// deep inside a 5 MB binary.
    static let release = "v$version"

#if os(Linux) || os(Windows)
    static let source = #"""
HEADER
    cat "$work/bergamot-translator.js"
    cat <<'FOOTER'
"""#
#else
    static let source = ""
#endif
}
FOOTER
} > "$out/BergamotGlue.swift"

ls -l "$out"
